apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: helical-theater-327410
  artifacts:
    - image: veyronworld/backend
      context: api
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
